### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by lolasj12491294** [LegoHacks/RoBeats-CS#1]
``
local getNoteType do 
    local f = library.flags;
    
    local enum_res = {
        missResult = 1;
        badResult = 2;
        goodResult = 3;
        greatResult = 4;
        perfectResult = 5;
        marvelousResult = 6;
    };
    
    local mapped_e = {
        enum_res.marvelousResult;
        enum_res.perfectResult;
        enum_res.greatResult;
        enum_res.goodPercentage;
    };

    function getNoteType()
        local r = Random.new();
        for i,v in ipairs{f.marvelousPercentage, f.perfectPercentage, f.greatPercentage, f.goodPercentage, } do
            if (r:NextNumber(0, 100) <= v) then
                return mapped_e[i];
            end;
        end;
        return 0;
    end;
end;
``
jk

**Comment by Spencer-0003** [comment]
Didn't think of doing that, will add :)
